# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 07:41
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fias', '0015_auto_20161224_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrobjindex',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
